services:
  - type: web
    name: mp3-downloader
    runtime: python
    plan: free
    region: singapore # Change this to your preferred region
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
